# Generated by Django 4.2.5 on 2023-09-22 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('post', 'Post'), ('receta', 'Receta')], default='receta', max_length=10)),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo de la publicación')),
                ('subtitulo', models.CharField(max_length=100, verbose_name='Subtitulo de la publicación')),
                ('copy', models.TextField(verbose_name='Contenido de la publicación')),
                ('autor', models.CharField(max_length=50, verbose_name='Nombre del autor')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('imagen', models.ImageField(upload_to='imagenes/', verbose_name='Imagen de la publicación')),
                ('ingredientes', models.TextField(blank=True, null=True, verbose_name='Ingredientes de la receta')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Video de la publicacion')),
            ],
        ),
    ]
